steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/cloud-build-demo-230104/my-image1', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/cloud-build-demo-230104/my-image1']
tags: ['mytag1']

